require 'rake/clean'

CC = 'clang'
FLEX = 'flex'

TARGETS = %w(
test
xml-entitify
xml-deentitify
search-nums
hiki-outliner
)

CLEAN.include('*.yy.c')
CLOBBER.include(TARGETS)

TARGETS.each do |target|
  yy_c = "#{target}.yy.c"

  file(target => yy_c) do
    sh(CC, '-o', target, yy_c)
  end
end

rule('.yy.c' => '%{\.yy$,}X.l') do |t|
  sh(FLEX, '-o', t.name, t.source)
end
